=== 2052sagar/developer-events/2023/Open-Standards-Code-Sprint/muddi/NUAR logical model and encodings/GML/Codelist Register/Codelist_Register_DataManagement.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://portal.nuar.uk/schemas/nuarcodelists_datamanagement/2.1.0" targetNamespace="http://portal.nuar.uk/schemas/nuarcodelists_datamanagement/2.1.0" elementFormDefault="qualified">
<xs:element name="xml-tables" type="xml-tablesType"/>
<xs:element name="nuarcodelists_datamanagement.submissionresultvalue-table" type="nuarcodelists_datamanagement.submissionresultvalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.submissionresultvalue" type="nuarcodelists_datamanagement.submissionresultvalueType"/>
<xs:element name="nuarcodelists_datamanagement.submissionstatusvalue-table" type="nuarcodelists_datamanagement.submissionstatusvalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.submissionstatusvalue" type="nuarcodelists_datamanagement.submissionstatusvalueType"/>
<xs:element name="nuarcodelists_datamanagement.submissionreplacementscopevalue-table" type="nuarcodelists_datamanagement.submissionreplacementscopevalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.submissionreplacementscopevalue" type="nuarcodelists_datamanagement.submissionreplacementscopevalueType"/>
<xs:element name="nuarcodelists_datamanagement.lifecyclestatusvalue-table" type="nuarcodelists_datamanagement.lifecyclestatusvalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.lifecyclestatusvalue" type="nuarcodelists_datamanagement.lifecyclestatusvalueType"/>
<xs:element name="nuarcodelists_datamanagement.submissiontypevalue-table" type="nuarcodelists_datamanagement.submissiontypevalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.submissiontypevalue" type="nuarcodelists_datamanagement.submissiontypevalueType"/>
<xs:element name="nuarcodelists_datamanagement.publicationstagestatusvalue-table" type="nuarcodelists_datamanagement.publicationstagestatusvalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.publicationstagestatusvalue" type="nuarcodelists_datamanagement.publicationstagestatusvalueType"/>
<xs:element name="nuarcodelists_datamanagement.publicationresultvalue-table" type="nuarcodelists_datamanagement.publicationresultvalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.publicationresultvalue" type="nuarcodelists_datamanagement.publicationresultvalueType"/>
<xs:element name="nuarcodelists_datamanagement.publicationstatusvalue-table" type="nuarcodelists_datamanagement.publicationstatusvalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.publicationstatusvalue" type="nuarcodelists_datamanagement.publicationstatusvalueType"/>
<xs:element name="nuarcodelists_datamanagement.datasettypevalue-table" type="nuarcodelists_datamanagement.datasettypevalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.datasettypevalue" type="nuarcodelists_datamanagement.datasettypevalueType"/>
<xs:element name="nuarcodelists_datamanagement.publicationstagevalue-table" type="nuarcodelists_datamanagement.publicationstagevalue-tableType"/>
<xs:element name="nuarcodelists_datamanagement.publicationstagevalue" type="nuarcodelists_datamanagement.publicationstagevalueType"/>
<xs:complexType name="xml-tablesType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.submissionresultvalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.submissionstatusvalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.submissionreplacementscopevalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.lifecyclestatusvalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.submissiontypevalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.publicationstagestatusvalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.publicationresultvalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.publicationstatusvalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.datasettypevalue-table" minOccurs="0"/>
<xs:element ref="nuarcodelists_datamanagement.publicationstagevalue-table" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissionresultvalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.submissionresultvalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissionresultvalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissionstatusvalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.submissionstatusvalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissionstatusvalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissionreplacementscopevalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.submissionreplacementscopevalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissionreplacementscopevalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.lifecyclestatusvalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.lifecyclestatusvalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.lifecyclestatusvalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissiontypevalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.submissiontypevalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.submissiontypevalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationstagestatusvalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.publicationstagestatusvalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationstagestatusvalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationresultvalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.publicationresultvalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationresultvalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationstatusvalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.publicationstatusvalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationstatusvalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.datasettypevalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.datasettypevalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.datasettypevalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationstagevalue-tableType">
<xs:sequence>
<xs:element ref="nuarcodelists_datamanagement.publicationstagevalue" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="nuarcodelists_datamanagement.publicationstagevalueType">
<xs:sequence>
<xs:element name="systemid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="38"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="value" minOccurs="0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>

=== 2052sagar/developer-events/2023/Open-Standards-Code-Sprint/muddi/NUAR logical model and encodings/GML/Codelist Register/Codelist_Register_DataManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<xml-tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://portal.nuar.uk/schemas/nuarcodelists_datamanagement/2.1.0" xsi:schemaLocation="http://portal.nuar.uk/schemas/nuarcodelists_datamanagement/2.1.0 Codelist_Register_DataManagement.xsd">
<nuarcodelists_datamanagement.submissionresultvalue-table>
<nuarcodelists_datamanagement.submissionresultvalue>
<systemid>c8279a63-8b85-4114-a978-4be517023f36</systemid>
<value>Success</value>
</nuarcodelists_datamanagement.submissionresultvalue>
<nuarcodelists_datamanagement.submissionresultvalue>
<systemid>093fe52f-d02c-45ca-98b3-c5f4c0780ef3</systemid>
<value>Failure</value>
</nuarcodelists_datamanagement.submissionresultvalue>
<nuarcodelists_datamanagement.submissionresultvalue>
<systemid>23fdb55c-466c-489a-8bf1-2bfc38d403a9</systemid>
<value>Unknown</value>
</nuarcodelists_datamanagement.submissionresultvalue>
</nuarcodelists_datamanagement.submissionresultvalue-table>
<nuarcodelists_datamanagement.submissionstatusvalue-table>
<nuarcodelists_datamanagement.submissionstatusvalue>
<systemid>c21b5b6a-e150-47fc-b906-67f010202516</systemid>
<value>Starting</value>
</nuarcodelists_datamanagement.submissionstatusvalue>
<nuarcodelists_datamanagement.submissionstatusvalue>
<systemid>7c48d1c1-8969-4a45-a9e3-2a0d9c3cd837</systemid>
<value>In Progress</value>
</nuarcodelists_datamanagement.submissionstatusvalue>
<nuarcodelists_datamanagement.submissionstatusvalue>
<systemid>cd2a83f5-6e8f-4211-a2fa-14f697ba2b2a</systemid>
<value>Paused</value>
</nuarcodelists_datamanagement.submissionstatusvalue>
<nuarcodelists_datamanagement.submissionstatusvalue>
<systemid>c0dc186c-f344-4b48-8af4-45376c994865</systemid>
<value>Finishing</value>
</nuarcodelists_datamanagement.submissionstatusvalue>
<nuarcodelists_datamanagement.submissionstatusvalue>
<systemid>bd670ca5-25f3-496f-a518-162854c58832</systemid>
<value>Completed</value>
</nuarcodelists_datamanagement.submissionstatusvalue>
</nuarcodelists_datamanagement.submissionstatusvalue-table>
<nuarcodelists_datamanagement.submissionreplacementscopevalue-table>
<nuarcodelists_datamanagement.submissionreplacementscopevalue>
<systemid>82362fea-bde2-4edc-b396-ce5f8c26f0f7</systemid>
<value>None</value>
</nuarcodelists_datamanagement.submissionreplacementscopevalue>
<nuarcodelists_datamanagement.submissionreplacementscopevalue>
<systemid>c84829e3-e1e2-4d37-9864-ffd5502906b7</systemid>
<value>Organisation</value>
</nuarcodelists_datamanagement.submissionreplacementscopevalue>
<nuarcodelists_datamanagement.submissionreplacementscopevalue>
<systemid>f3b91d3d-27cc-44f1-986a-c311bb2111ee</systemid>
<value>Submission</value>
</nuarcodelists_datamanagement.submissionreplacementscopevalue>
<nuarcodelists_datamanagement.submissionreplacementscopevalue>
<systemid>c8be62a9-fe77-4161-b351-6953918a52fe</systemid>
<value>Dataset</value>
</nuarcodelists_datamanagement.submissionreplacementscopevalue>
<nuarcodelists_datamanagement.submissionreplacementscopevalue>
<systemid>3320456f-932e-4fe1-aa3d-4b4e0204d7a4</systemid>
<value>Area</value>
</nuarcodelists_datamanagement.submissionreplacementscopevalue>
<nuarcodelists_datamanagement.submissionreplacementscopevalue>
<systemid>3d9ca075-6c96-4d5a-b436-dce20e6b6a09</systemid>
<value>Feature</value>
</nuarcodelists_datamanagement.submissionreplacementscopevalue>
</nuarcodelists_datamanagement.submissionreplacementscopevalue-table>
<nuarcodelists_datamanagement.lifecyclestatusvalue-table>
<nuarcodelists_datamanagement.lifecyclestatusvalue>
<systemid>71349986-9af2-408d-a1d3-bc3c1db9b576</systemid>
<value>Submitted</value>
</nuarcodelists_datamanagement.lifecyclestatusvalue>
<nuarcodelists_datamanagement.lifecyclestatusvalue>
<systemid>d0b64670-eaa5-40cc-aec0-aa05e2916d1f</systemid>
<value>Publishable</value>
</nuarcodelists_datamanagement.lifecyclestatusvalue>
<nuarcodelists_datamanagement.lifecyclestatusvalue>
<systemid>dbee7d15-1539-400b-b4e0-afbe10035a63</systemid>
<value>Retired</value>
</nuarcodelists_datamanagement.lifecyclestatusvalue>
<nuarcodelists_datamanagement.lifecyclestatusvalue>
<systemid>49de85db-cc4e-4637-bde9-67687a98f202</systemid>
<value>Archived</value>
</nuarcodelists_datamanagement.lifecyclestatusvalue>
<nuarcodelists_datamanagement.lifecyclestatusvalue>
<systemid>750bc561-483e-4e9b-be63-df710b8a7e09</systemid>
<value>Deleted</value>
</nuarcodelists_datamanagement.lifecyclestatusvalue>
</nuarcodelists_datamanagement.lifecyclestatusvalue-table>
<nuarcodelists_datamanagement.submissiontypevalue-table>
<nuarcodelists_datamanagement.submissiontypevalue>
<systemid>82559ad8-cf21-4b67-8f70-9467ac170d6d</systemid>
<value>Asset Data</value>
</nuarcodelists_datamanagement.submissiontypevalue>
<nuarcodelists_datamanagement.submissiontypevalue>
<systemid>d66407a5-ee13-4c21-8a90-773a0da4513e</systemid>
<value>Contact Details</value>
</nuarcodelists_datamanagement.submissiontypevalue>
<nuarcodelists_datamanagement.submissiontypevalue>
<systemid>3618a87b-cab4-416d-b63c-1fde9ee10ca1</systemid>
<value>Service Areas</value>
</nuarcodelists_datamanagement.submissiontypevalue>
<nuarcodelists_datamanagement.submissiontypevalue>
<systemid>508ecc00-c306-472c-8e7f-8df2a270bf88</systemid>
<value>Backdrop Mapping</value>
</nuarcodelists_datamanagement.submissiontypevalue>
<nuarcodelists_datamanagement.submissiontypevalue>
<systemid>c1afffc6-828d-4043-a666-1cfaccc0cad0</systemid>
<value>Supplementary Data</value>
</nuarcodelists_datamanagement.submissiontypevalue>
</nuarcodelists_datamanagement.submissiontypevalue-table>
<nuarcodelists_datamanagement.publicationstagestatusvalue-table>
<nuarcodelists_datamanagement.publicationstagestatusvalue>
<systemid>da1c37ec-91bf-436f-b893-3ea1171821d9</systemid>
<value>In Progress</value>
</nuarcodelists_datamanagement.publicationstagestatusvalue>
<nuarcodelists_datamanagement.publicationstagestatusvalue>
<systemid>df3f7a73-28d7-47dd-9771-cfda4749e20a</systemid>
<value>Completed</value>
</nuarcodelists_datamanagement.publicationstagestatusvalue>
<nuarcodelists_datamanagement.publicationstagestatusvalue>
<systemid>b1b5e560-02f8-4167-a1c1-6408e56e741d</systemid>
<value>Error</value>
</nuarcodelists_datamanagement.publicationstagestatusvalue>
<nuarcodelists_datamanagement.publicationstagestatusvalue>
<systemid>e4df9d74-7521-4847-b7bf-e65323e5b194</systemid>
<value>Duplicate</value>
</nuarcodelists_datamanagement.publicationstagestatusvalue>
</nuarcodelists_datamanagement.publicationstagestatusvalue-table>
<nuarcodelists_datamanagement.datasettypevalue-table>
<nuarcodelists_datamanagement.datasettypevalue>
<systemid>f45b41c3-a355-4864-8569-59ad6d1833f7</systemid>
<value>CAD</value>
</nuarcodelists_datamanagement.datasettypevalue>
<nuarcodelists_datamanagement.datasettypevalue>
<systemid>1ef742f5-0d03-48cd-8be4-6bf751a96dd6</systemid>
<value>Documents</value>
</nuarcodelists_datamanagement.datasettypevalue>
<nuarcodelists_datamanagement.datasettypevalue>
<systemid>4b15874c-ecdd-4b76-ac04-b00af35615ec</systemid>
<value>GIS Vector</value>
</nuarcodelists_datamanagement.datasettypevalue>
<nuarcodelists_datamanagement.datasettypevalue>
<systemid>a784ef6c-7960-4f23-83c8-a4e24b714732</systemid>
<value>Raster</value>
</nuarcodelists_datamanagement.datasettypevalue>
</nuarcodelists_datamanagement.datasettypevalue-table>
<nuarcodelists_datamanagement.publicationstagevalue-table>
<nuarcodelists_datamanagement.publicationstagevalue>
<systemid>fb8cb781-ddfe-43aa-978c-f6b015e800ac</systemid>
<value>dti-holding</value>
</nuarcodelists_datamanagement.publicationstagevalue>
<nuarcodelists_datamanagement.publicationstagevalue>
<systemid>a88522b9-35f4-49e5-a7aa-2ea34d135585</systemid>
<value>holding-standby</value>
</nuarcodelists_datamanagement.publicationstagevalue>
<nuarcodelists_datamanagement.publicationstagevalue>
<systemid>e3554c75-8ee1-441d-a712-3ff5873b4dda</systemid>
<value>live-standby-swap</value>
</nuarcodelists_datamanagement.publicationstagevalue>
<nuarcodelists_datamanagement.publicationstagevalue>
<systemid>6418e511-d469-45cb-9638-0433c46f1b03</systemid>
<value>live-standby</value>
</nuarcodelists_datamanagement.publicationstagevalue>
</nuarcodelists_datamanagement.publicationstagevalue-table>
</xml-tables>
